### ISSUE TITLE
issue: Swagger email update

### ISSUE THREAD

**Issue by mariorguezari** [AriHealth/keycloak-auth#10]
# Issue report

**Expected Behavior**

The swagger UI should show a valid email.

**Actual Behavior**

The current email is going to disappear shortly.

**Steps to Reproduce the Problem**

  1. net.atos.ari.auth.config.Swagger2Config.java

**Logs**

```
.contact(new Contact("Atos ARI Health", "http://booklet.atosresearch.eu/content/health-0", 
"ana.quintero@atos.net"))
```

**Comment by miquinti** [comment]
Right "ana.quintero" will disappear, but, should we keep an email address and which one?

**Comment by mariorguezari** [comment]
In my opinion, a mailbox for the group would be the ideal solution, but we don't have it. 
In the meanwhile, we can choose not to provide any real email address by default.

**Comment by carloscaverobarca** [comment]
Remove the email address from the Swagger configuration (I guess it is not really needed). Later on we can consider to put a generic one (the github account for the organization?)
